models/Competition.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use Yii;

class Competition extends ActiveRecord
{
    public function getCompetitionById($id){
        $competition = Yii::$app->db->createCommand('SELECT * FROM `competition` 
            JOIN `type_competition` ON `competition`.`id_type_competition` = `type_competition`.`id`
            JOIN `user` ON `competition`.`id_creator`= `user`.`id`
            WHERE `competition`.`id_competition` = :id_competition',
            [':id_competition' => $id])->queryAll();
        return $competition;
    }
    public function getBrieflyCompetitions(){
        $competitions = Yii::$app->db->createCommand('SELECT * FROM `competition` 
            JOIN `type_competition` ON `competition`.`id_type_competition` = `type_competition`.`id`
            JOIN `user` ON `competition`.`id_creator`= `user`.`id`
            WHERE `competition`.`is_checked` = \'1\'')->queryAll();
        return $competitions;
    }
    public function getAwardsById($id){
        $awards = Yii::$app->db->createCommand('SELECT `award`.`name` FROM `competition_award` 
            JOIN `competition` ON `competition_award`.`id_competition` = `competition`.`id_competition`
            JOIN `award` ON `competition_award`.`id_award`= `award`.`id`
            WHERE `competition`.`id_competition` = :id_competition',
            [':id_competition' => $id])->queryAll();
        return $awards;
    }
    public function getSponsorsById($id){
        $sponsors = Yii::$app->db->createCommand('SELECT `sponsor`.`name` FROM `competition_sponsor` 
            JOIN `competition` ON `competition_sponsor`.`id_competition` = `competition`.`id_competition`
            JOIN `sponsor` ON `competition_sponsor`.`id_sponsor`= `sponsor`.`id`
            WHERE `competition`.`id_competition` = :id_competition',
            [':id_competition' => $id])->queryAll();
        return $sponsors;
    }
    public function addParticipant($id_competition){
        $competition = Yii::$app->db->createCommand('SELECT * FROM `user_competition` 
            WHERE `user_competition`.`id_user` = :id_user AND `user_competition`.`id_competition` = :id_competition',
            [':id_competition' => $id_competition, ':id_user' => Yii::$app->user->identity['id']])->queryAll();
        if(!$competition) {
            Yii::$app->db->createCommand('INSERT INTO `user_competition` (`id_user`, `id_competition`)
                VALUES (:id_user,:id_competition)',
                [':id_competition' => $id_competition, ':id_user' => Yii::$app->user->identity['id']])->query();
        }
        return true;
    }
    public function getParticipantsById($id_competition){
        $participants =  Yii::$app->db->createCommand('SELECT * FROM `user_competition` 
            JOIN `user` ON `user_competition`.`id_user` = `user`.`id`
            WHERE `user_competition`.`id_competition` = :id_competition',
            [':id_competition' => $id_competition])->queryAll();
        return $participants;
    }
}

controllers/CompetitionController.php
<?php

namespace app\controllers;

use app\models\TypeCompetition;
use yii\web\Controller;
use app\models\Competition;
use app\models\CompetitionCreatingForm;
use Yii;
use yii\web\ForbiddenHttpException;

class CompetitionController extends Controller
{
    public function actionIndex()
    {
        $competition_model = new Competition();
        $competitions = $competition_model->getBrieflyCompetitions();
        return $this->render('index', compact('competitions'));
    }

    public function actionView($id)
    {
        $competition_model = new Competition();
        $competition = $competition_model->getCompetitionById($id);
        $awards = $competition_model->getAwardsById($id);
        $sponsors = $competition_model->getSponsorsById($id);
        return $this->render('view', compact('competition', 'awards', 'sponsors', 'participants'));
    }

    public function actionViewParticipants($id)
    {
        $competition_model = new Competition();
        $competition = $competition_model->getCompetitionById($id);
        $participants = $competition_model->getParticipantsById($id);
        return $this->render('view-participants', compact('participants', 'competition'));
    }

    public function actionCreating()
    {
        $flagProhibition = false;
        if (Yii::$app->user->can('createCompetition')) {
            $typesCompetitionsQuery = TypeCompetition::find()->select(['type_name'])->asArray()->all();
            for ($i = 0; $i < count($typesCompetitionsQuery); $i++) {
                $types_competitions[$i + 1] = $typesCompetitionsQuery[$i]['type_name'];
            }
            $creatingForm = new CompetitionCreatingForm();
            if (isset($_POST['CompetitionCreatingForm'])) {
                $creatingForm->attributes = Yii::$app->request->post('CompetitionCreatingForm');
                if ($creatingForm->validate() && $creatingForm->signUp()) {
                    return $this->redirect('/competitions');
                }
            }
            return $this->render('creating', compact('creatingForm',
                'flagProhibition', 'types_competitions'));
        } else {
            $flagProhibition = true;
            return $this->render('creating', compact('flagProhibition'));
        }
    }

    public function actionCompleted()
    {
        $competition_model = new Competition();
        $competitions = $competition_model->getBrieflyCompetitions();
        return $this->render('completed', compact('competitions'));
    }

    public function actionAddParticipant($id_competition)
    {
        $competition_model = new Competition();
        $competition_model->addParticipant($id_competition);
        return true;
    }
}

views/competition/completed.php
<?php

$this->title = 'Завершенные соревнования';
use yii\helpers\Url;
use yii\widgets\Pjax;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => false,
]); ?>
    <section class="competitions">
        <div class="container-fluid">
            <h3 align="center"><a href="<?= Url::to(['/competitions']) ?>">Список соревнований</a>
                | <a href="<?= Url::to(['/competitions/creating']) ?>">Создать соревнование</a> | Завершенные соревнования</h3>
            <div class="competition-block">
                <table width="100%" cellpadding="5" border="1">
                    <tr>
                        <th>Город</th>
                        <th>Название</th>
                        <th>Создатель</th>
                        <th>Тип соревнования</th>
                        <th>Дата проведения</th>
                        <th>Возрастные ограничения</th>
                        <th></th>
                    </tr>
                    <?php
                    if(!empty($competitions))
                        foreach ($competitions as $competition):
                            if ($competition['date'] < date('Y-m-d')):
                    ?>
                            <tr>
                                <td><?=$competition['city'];?></td>
                                <td><?=$competition['competition_name'];?></td>
                                <td><a href="<?= Url::to(['/site/view-user', 'id' => $competition['id_creator']]) ?>"><?=$competition['login'];?></a></td>
                                <td><?=$competition['type_name'];?></td>
                                <td><?=(new DateTime($competition['date']))->format('d.m.Y'); ?></td>
                                <td>От <?=$competition['age_from'];?> до <?=$competition['age_to'];?> лет</td>
                                <td><a data-pjax="0" href="<?= Url::to(['/competition/view', 'id' => $competition['id_competition']]) ?>" class="btn btn-success">Подробнее</a></td>
                            </tr>

                        <?php
                            endif;
                            endforeach;
                        ?>
                </table>
            </div>
        </div>
    </section>
<?php Pjax::end();?>

views/competition/creating.php
<?php
$this->title = 'Создание соревнования';

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;
use kartik\date\DatePicker;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => false,
]); ?>
<div class="container-fluid">
    <h3 align="center"><a href="<?= Url::to(['/competitions']) ?>">Список соревнований</a> | Создать соревнование
        | <a href="<?= Url::to(['/competitions/completed']) ?>">Завершенные соревнования</a></h3>
    <?php if(!$flagProhibition): ?>
        <div class="col-md-5 col-md-offset-4 form-creating">
            <?php
            $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration-form']);
            ?>
            <?= $form->field($creatingForm, 'competition_name'); ?>
            <?= $form->field($creatingForm, 'city'); ?>
            <?= $form->field($creatingForm, 'id_type_competition')->dropDownList($types_competitions,
                [
                    'prompt' => 'Выберите тип соревнования'
                ]); ?>
            <?= $form->field($creatingForm, 'date')->widget(DatePicker::className(), [
                'type' => DatePicker::TYPE_INPUT,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($creatingForm, 'age_from')
                ->textInput(['placeholder' => 'Введите одно число, например 14']); ?>
            <?= $form->field($creatingForm, 'age_to')
                ->textInput(['placeholder' => 'Введите одно число, например 18']); ?>
            <div>
                <button type="submit" class="btn btn-primary">Создать соревнование</button>
            </div>
            <?php
            ActiveForm::end();
            ?>
        </div>
    <?php else: ?>
        <p align="center" class="log_in">Вы не можете создавать соревнования.</p>
    <?php endif; ?>
</div>
<?php Pjax::end();?>

views/competition/index.php
<?php

$this->title = 'Соревнования';
use yii\helpers\Url;
use yii\widgets\Pjax;
?>
<?php Pjax::begin([
        'timeout' => 5000,
        'clientOptions' => ['method' => 'POST'],
        'enablePushState' => false,
]); ?>
<section class="competitions">
    <div class="container-fluid">
        <h3 align="center">Список соревнований | <a href="<?= Url::to(['/competitions/creating']) ?>">Создать соревнование</a>
            | <a href="<?= Url::to(['/competitions/completed']) ?>">Завершенные соревнования</a></h3>
            <div class="competition-block">
                <table width="100%" cellpadding="5" border="1">
                   <tr>
                       <th>Город</th>
                       <th>Название</th>
                       <th>Создатель</th>
                       <th>Тип соревнования</th>
                       <th>Дата проведения</th>
                       <th>Возрастные ограничения</th>
                       <th></th>
                   </tr>
                    <?php
                    if(!empty($competitions))
                    foreach ($competitions as $competition):
                        if ($competition['date'] >= date('Y-m-d')):
                    ?>
                   <tr>
                       <td><?=$competition['city'];?></td>
                       <td><?=$competition['competition_name'];?></td>
                       <td><a href="<?= Url::to(['site/view-user', 'id' => $competition['id_creator']]) ?>"><?=$competition['login'];?></a></td>
                       <td><?=$competition['type_name'];?></td>
                       <td><?=(new DateTime($competition['date']))->format('d.m.Y'); ?></td>
                       <td>От <?=$competition['age_from'];?> до <?=$competition['age_to'];?> лет</td>
                       <td><a data-pjax="0" href="<?= Url::to(['/competition/view',
                               'id' => $competition['id_competition']]) ?>"
                              class="btn btn-success">Подробнее / Принять участие</a></td>
                  </tr>
                    <?php
                        endif;
                        endforeach;
                    ?>
                 </table>
            </div>
    </div>
</section>
<?php Pjax::end();?>

views/competition/view-participants.php
<?php
$this->title = $competition[0]['competition_name'];

use yii\helpers\Url;
use yii\widgets\Pjax;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => true,
]); ?>
<div class="container-fluid">
    <h3 align="center"><a href="<?= Url::to(['/competition/view', 'id' => $competition[0]['id_competition']]) ?>">
        Сведения о соревновании</a> | Участники соревнования
        <?php if($competition[0]['id_creator'] == Yii::$app->user->identity['id']):?>
         | <a href="<?= Url::to(['/protocol/index', 'id' => $competition[0]['id_competition']]) ?>">
                Объявить результат
            </a>
        <?php endif;?>
    </h3>
        <div class="view_participants">
            <h2><?= $competition[0]['competition_name']?></h2>
            <table width="60%" cellpadding="5">
                <tr>
                    <th>ФИО</th>
                    <th>Логин</th>
                    <th>Результат</th>
                    <th>Место</th>
                </tr>
                 <?php
                    foreach ($participants as $participant):
                 ?>
                <tr>
                    <td><?=$participant['last_name']. ' '. $participant['name']. ' '. $participant['patronymic'];?></td>
                    <td><a href="<?= Url::to(['/site/view-user', 'id' => $participant['id']]) ?>"><?=$participant['login']?></a></td>
                    <?php if($participant['result'] != null):?>
                        <td><?= $participant['result']?></td>
                    <?php endif;?>
                    <?php if($participant['place'] != null):?>
                        <td><?= $participant['place']?></td>
                    <?php endif;?>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
</div>
<?php Pjax::end();?>

views/competition/view.php
<?php
$this->title = $competition[0]['competition_name'];

use yii\helpers\Url;
use yii\widgets\Pjax;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => true,
]); ?>
<div class="container-fluid">
    <h3 align="center">Сведения о соревновании |<a href="<?= Url::to(['/competition/view-participants',
            'id' => $competition[0]['id_competition']]) ?>"> Участники соревнования</a>
        <?php if($competition[0]['id_creator'] == Yii::$app->user->identity['id']):?>
            | <a href="<?= Url::to(['/protocol/index', 'id' => $competition[0]['id_competition']]) ?>">
                Объявить результат
            </a>
        <?php endif;?>
    </h3>
    <div class="col-sm-4 col-sm-offset-4">
        <div class="competition_view">
            <h2><?= $competition[0]['competition_name']?></h2>
            <ul>
                <li><h4>Город:</h4> <p><?= $competition[0]['city']?></p></li>
                <li>
                    <h4>Логин создателя соревнования:</h4>
                    <p>
                        <?= $competition[0]['last_name']?>
                        <?= $competition[0]['name']?>
                        <?= $competition[0]['patronymic']?>
                        <a href="<?= Url::to(['/site/view-user', 'id' => $competition[0]['id_creator']]) ?>">
                            <?= '( '.$competition[0]['login'].' )'?></a>
                    </p>
                </li>
                <li><h4>Тип соревнования:</h4> <p><?= $competition[0]['type_name']?></p></li>
                <li><h4>Дата проведения:</h4> <p><?= $competition[0]['date']?></p></li>
                <li><h4>Необходимый взнос:</h4> <p><?= $competition[0]['contribution']?></p></li>
                <li><h4>Возрастные ограничения:</h4> <p>От <?= $competition[0]['age_from']?> До <?= $competition[0]['age_to']?> лет</p></li>
                <li><h4>Описание соревнования:</h4> <p><?= $competition[0]['description']?></p></li>
                <li><h4>Типы наград:</h4>
                    <p>
                        <?php
                            foreach ($awards as $award)
                                echo $award['name'].', ';
                        ?>
                    </p>
                </li>
                <li><h4>Спонсоры:</h4>
                <p>
                   <?php
                        foreach ($sponsors as $sponsor)
                            echo $sponsor['name'].', ';
                    ?>
                </p>
                </li>
                <?php  if ($competition[0]['date'] >= date('Y-m-d')): ?>
                <a data-id_competition="<?=$competition[0]['id_competition']?>" href="<?= Url::to(['/competition/add-participant', 'id_competition' => $competition[0]['id_competition']]) ?>"
                   class="btn btn-success add_participant">Принять участие</a><br/>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>
<?php Pjax::end();?>

<!--    <div class="col-md-3 col-md-offset-4">-->
<!--        <div class="competition_participants">-->
<!--            --><?php
//            foreach ($participants as $participant):
//                echo $participant['last_name']. ' '. $participant['name']. ' '. $participant['patronymic'].
//                    ' (';
//                ?>
<!--                <a href="--><?//= Url::to(['/site/view-user', 'id' => $participant['id']]) ?><!--">--><?//=$participant['login']?><!--</a>-->
<!--                --><?//= ')'; ?><!--<br/>-->
<!--            --><?php //endforeach; ?>
<!--        </div>-->
<!--    </div>-->

<!--<div class="slide">-->
<!--    <label for="slide1">-->
<!--        Показать участников соревнования-->
<!--    </label>-->
<!--    <input type="checkbox" id="slide1"/>-->
<!--    <p class="content">-->
<!--        --><?php
//        foreach ($participants as $participant):
//            echo $participant['last_name']. ' '. $participant['name']. ' '. $participant['patronymic'].
//                ' (';
//            ?>
<!--            <a href="--><?//= Url::to(['/site/view-user', 'id' => $participant['id']]) ?><!--">--><?//=$participant['login']?><!--</a>-->
<!--            --><?//= ')'; ?><!--<br/>-->
<!--        --><?php //endforeach; ?>
<!--    </p>-->
<!--</div>-->