models/Challenge.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

class Challenge extends ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['date_creation'],
                ],
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function getChallenges(){
        $challenges = Yii::$app->db->createCommand('SELECT * FROM `challenge` 
            JOIN `user` ON `challenge`.`id_creator` = `user`.`id`
            WHERE `challenge`.`is_checked` = \'1\'
            ORDER BY `challenge`.`date_creation`')->queryAll();
        return $challenges;
    }

    public function getChallengeById($id){
        $challenge = Yii::$app->db->createCommand('SELECT * FROM `challenge` 
            JOIN `user` ON `challenge`.`id_creator` = `user`.`id`
            WHERE `challenge`.`id_challenge` = :id_challenge',
            [':id_challenge' => $id])->queryAll();
        return $challenge;
    }
}

controllers/ChallengeController.php
<?php

namespace app\controllers;

use app\models\Challenge;
use app\models\ChallengeCreatingForm;
use app\models\ChallengeParticipantForm;
use app\models\ChallengeParticipation;
use Yii;
use yii\web\Controller;

class ChallengeController extends Controller
{
    public function actionIndex()
    {
        $challengeModel = new Challenge();
        $challenges = $challengeModel->getChallenges();
        return $this->render('index', compact('challenges'));
    }

    public function actionCreating()
    {
        $creatingForm = new ChallengeCreatingForm();
        if (isset($_POST['ChallengeCreatingForm'])) {
            $creatingForm->attributes = Yii::$app->request->post('ChallengeCreatingForm');
            if ($creatingForm->validate() && $creatingForm->signUp()) {
                return $this->redirect('/challenges');
            }
        }
        return $this->render('creating', compact('creatingForm'));
    }

    public function actionView($id)
    {
        $challengeModel = new Challenge();
        $challengeParticipationModel = new ChallengeParticipation();

        $challenge = $challengeModel->getChallengeById($id);
        $challengeParticipations = $challengeParticipationModel->getChallengeById($id);
        return $this->render('view', compact('challenge', 'challengeParticipations'));
    }

    public function actionTakingPart($id)
    {
        $this->layout = false;
        $participantForm = new ChallengeParticipantForm();
        if (isset($_POST['ChallengeParticipantForm'])) {
            $participantForm->attributes = Yii::$app->request->post('ChallengeParticipantForm');
            if ($participantForm->validate() && $participantForm->takePart($id)) {
                $url = '/challenges/view?id=' . $id;
                return $this->redirect($url);
            }
        }
        return $this->render('taking-part', compact('participantForm'));
    }
}

views/challenge/creating.php
<?php
$this->title = 'Создание челленджа';

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;
use kartik\date\DatePicker;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => false,
]); ?>
    <div class="container-fluid">
        <h3 align="center"><a href="<?= Url::to(['/challenge/index']) ?>">Список челленджей</a>
            | Создать челлендж</h3>
            <div class="col-md-5 col-md-offset-4 form-creating">
                <?php
                $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration-form']);
                ?>
                <?= $form->field($creatingForm, 'name_challenge')
                    ->textInput(['placeholder' => 'Введите название челленджа, например "жим лежа 100x100"']); ?>
                <?= $form->field($creatingForm, 'video_reference')
                    ->textInput(['placeholder' => 'Введите ссылку на Youtube-видео']); ?>
                <?= $form->field($creatingForm, 'description'); ?>
                <div>
                    <button type="submit" class="btn btn-primary">Создать челлендж</button>
                </div>
                <?php
                ActiveForm::end();
                ?>
            </div>
    </div>
<?php Pjax::end();?>

views/challenge/index.php
<?php

$this->title = 'Челленджи';
use yii\helpers\Url;
use yii\widgets\Pjax;
?>
<?php Pjax::begin([
    'timeout' => 5000,
    'clientOptions' => ['method' => 'POST'],
    'enablePushState' => false,
]); ?>
    <section class="challenges">
        <div class="container-fluid">
            <h3 align="center">Список челленджей
            <?php if(!Yii::$app->user->isGuest): ?>
                | <a href="<?= Url::to(['/challenge/creating']) ?>">Создать челлендж</a>
            <?php endif; ?>
            </h3>
            <div class="challenge-block">
                <table width="100%" cellpadding="5" border="1">
                    <tr>
                        <th>Название</th>
                        <th>Дата создания</th>
                        <th>Создатель</th>
                        <th>Видео</th>
                        <th>Описание</th>
                        <th></th>
                    </tr>
                    <?php
                    if(!empty($challenges))
                        foreach ($challenges as $challenge):
                                ?>
                                <tr>
                                    <td><?=$challenge['name_challenge'];?></td>
                                    <td><?=(new DateTime($challenge['date_creation']))->format('d.m.Y'); ?></td>
                                    <td><a href="<?= Url::to(['site/view-user', 'id' => $challenge['id_creator']]) ?>">
                                            <?=$challenge['login'];?></a></td>
                                    <td><iframe width="190" height="120" src="<?=$challenge['video_reference'];?>"
                                                frameborder="0" allow="accelerometer; autoplay;
                                                encrypted-media; gyroscope; picture-in-picture"
                                                allowfullscreen></iframe></td>
                                    <td><?=$challenge['description'];?></td>
                                    <td><a data-pjax="0" href="<?= Url::to(['/challenge/view',
                                            'id' => $challenge['id_challenge']]) ?>"
                                           class="btn btn-success">Подробнее / Принять участие</a></td>
                                </tr>
                            <?php
                        endforeach;
                    ?>
                </table>
            </div>
        </div>
    </section>
<?php Pjax::end();?>

views/challenge/taking-part.php
<?php
$this->title = 'Принять участие';

use yii\widgets\ActiveForm;

?>
<div class="container-fluid">
    <?php
    $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration_form']);
    ?>
    <?= $form->field($participantForm, 'video_reference'); ?>
    <div>
        <button type="submit" class="btn btn-primary">Принять участие</button>
    </div>
    <?php
    ActiveForm::end();
    ?>
</div>

views/challenge/view.php
<?php

$this->title = $challenge[0]['name_challenge'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $challenge['name_challenge']]);

use yii\helpers\Url;
use yii\bootstrap\Modal;
?>

<section class="challenge">
    <div class="container-fluid">
        <div class="row">
            <?php if(!empty($challenge)): ?>
                <iframe width="560" height="350" src="<?=$challenge[0]['video_reference'];?>"
                        frameborder="0" allow="accelerometer; autoplay;
                                                encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
        </div>
        <div class="row">
            <span class="challenge-block">
                <span class="headers_3"><?=$challenge[0]['name_challenge']; ?></span> <br/>
                    <span class="headers_4">Создатель:</span> <br/>
                <a href="<?= Url::to(['/site/view-user', 'id' => $challenge[0]['id_creator']]) ?>">
                    <?= $challenge[0]['login']; ?></a> <br/>
                    <span class="headers_4">Описание:</span> <br/>
                <?= $challenge[0]['description']; ?> <br/>
                <a href="#" onclick="return takePartChallenge(<?=$challenge[0]['id_challenge'];?>);"
                   class="btn btn-success">Принять участие</a> <br/>
                   <span class="headers_4">Участники:</span> <br/>
            </span>
            <?php endif; ?>
        </div>
            <div class="challenge_participation">
                <table width="70%" cellpadding="5" border="1">
                    <tr>
                        <th>Логин</th>
                        <th>Дата создания</th>
                        <th>Видео</th>
                    </tr>
                    <?php
                    if(!empty($challengeParticipations))
                        foreach ($challengeParticipations as $challengeParticipation):
                            ?>
                            <tr>
                                <td><a href="<?= Url::to(['/site/view-user',
                                        'id' => $challengeParticipation['id_participant']]) ?>">
                                        <?=$challengeParticipation['login'];?></a></td>
                                <td><?=$challengeParticipation['date_participation'];?></td>
                                <td><iframe width="190" height="120" src="<?=$challengeParticipation['video_reference'];?>"
                                            frameborder="0" allow="accelerometer; autoplay;
                                                encrypted-media; gyroscope; picture-in-picture"
                                            allowfullscreen></iframe></td>
                            </tr>
                        <?php
                        endforeach;
                    ?>
                </table>
            </div>
        </div>
</section>
<?php
Modal::begin([
    'header' => '<h2>Принять челлендж</h2>',
    'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
    'id' => 'modal-challenge-taking-part',
]);
Modal::end();
?>