controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ChangingPasswordForm;
use app\models\FightOfferExercise;
use app\models\ImageUploading;
use Yii;
use app\models\EditProfileForm;
use app\models\FightOffer;
use app\models\RegistrationForm;
use app\models\User;
use app\models\Article;
use yii\web\Controller;
use app\models\AuthorizationForm;
use yii\web\UploadedFile;


class SiteController extends Controller
{
    public function actionIndex()
    {
        $articles = Article::find()->where(['id_category' => 1])->asArray()->all();
        return $this->render('index', compact('articles'));
    }

    public function actionRegistration()
    {
        $registrationForm = new RegistrationForm();
        if (isset($_POST['RegistrationForm']) && $_POST['RegistrationForm']['acceptingRules'] == 1) {
            $registrationForm->attributes = Yii::$app->request->post('RegistrationForm');
            $time = (string)time();
            $token = md5($time);
            if ($registrationForm->validate() && $registrationForm->signUp($token) &&
                $registrationForm->verifyUser($token)) {
                return $this->redirect('authorization');
            }
        }
        return $this->render('registration', compact('registrationForm'));
    }

    public function actionRules()
    {
        return $this->render('rules');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest)
            return $this->goHome();
        $authorizationForm = new AuthorizationForm();
        if (isset($_POST['AuthorizationForm'])) {
            $authorizationForm->attributes = Yii::$app->request->post('AuthorizationForm');
            if ($authorizationForm->validate()) {
                Yii::$app->user->login($authorizationForm->getUser());
                return $this->goHome();
            }
        }
        return $this->render('authorization', compact('authorizationForm'));
    }

    public function actionLogout()
    {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->goHome();
        }
    }

    public function actionProfile()
    {
        $user = new User();
        $books = $user->getBooksByUserId(Yii::$app->user->identity['id']);
        $elements = $user->getElementsByUserId(Yii::$app->user->identity['id']);
        $offers = FightOffer::find()->where(['id_second_user' => Yii::$app->user->identity['id']])->all();
        $ownOffers = FightOffer::find()->where(['id_first_user' => Yii::$app->user->identity['id']])->all();
        $imageName = Yii::$app->user->identity['image_avatar'];
        return $this->render('profile', compact('books', 'elements',
            'offers', 'ownOffers', 'imageName'));
    }

    public function actionEditProfile()
    {
        $editProfileForm = new EditProfileForm();
        $imageUploadingModel = new ImageUploading();

        if (isset($_POST['EditProfileForm'])) {
            $editProfileForm->attributes = Yii::$app->request->post('EditProfileForm');

            $typeImage = 'editingProfile';
            $file = UploadedFile::getInstance($editProfileForm, 'image_avatar');
            if (!empty($file)) {
                $nameImage = $imageUploadingModel->uploadImage($file, $typeImage);
                $editProfileForm->image_avatar = $nameImage;
            }

            if ($editProfileForm->validate() && $editProfileForm->edit()) {
                return $this->goHome();
            }
        }
        return $this->render('edit-profile', compact('editProfileForm'));
    }

    public function actionShowBooks()
    {
        $this->layout = false;
        $user = new User();
        $books = $user->getBooksByUserId(Yii::$app->user->identity['id']);
        return $this->render('book-cart', compact('books'));
    }

    public function actionDeleteBook($id)
    {
        $this->layout = false;
        $user = new User();
        $user->deleteBook($id);
        $books = $user->getBooksByUserId(Yii::$app->user->identity['id']);
        return $this->render('book-cart', compact('books'));
    }

    public function actionShowElements()
    {
        $this->layout = false;
        $user = new User();
        $elements = $user->getElementsByUserId(Yii::$app->user->identity['id']);
        return $this->render('window-elements', compact('elements'));
    }

    public function actionDeleteElement($id)
    {
        $this->layout = false;
        $user = new User();
        $user->deleteElement($id);
        $elements = $user->getElementsByUserId(Yii::$app->user->identity['id']);
        return $this->render('window-elements', compact('elements'));
    }

    public function actionViewUser($id)
    {
        $user = User::findOne($id);
        return $this->render('view-user', compact('user'));
    }

    public function actionShowFightOffers()
    {
        $this->layout = false;
        $user = new User();
        $fightOfferExercisesModel = new FightOfferExercise();

        $offers = $user->getFightOffersBySecondUserId(Yii::$app->user->identity['id']);
        $exercises = $fightOfferExercisesModel->getFightOfferExercises();
        return $this->render('window-fightOffers', compact('offers', 'exercises'));
    }

    public function actionDeleteFightOffer($id)
    {
        $this->layout = false;
        $user = new User();
        $user->deleteFightOfferById($id);
        $offers = $user->getFightOffersBySecondUserId(Yii::$app->user->identity['id']);

        $fightOfferExercisesModel = new FightOfferExercise();
        $exercises = $fightOfferExercisesModel->getFightOfferExercises();

        return $this->render('window-fightOffers', compact('offers', 'exercises'));
    }

    public function actionAcceptFight($id)
    {
        $this->layout = false;
        $user = new User();
        $user->acceptOfferById($id);
        $offers = $user->getFightOffersBySecondUserId(Yii::$app->user->identity['id']);

        $fightOfferExercisesModel = new FightOfferExercise();
        $exercises = $fightOfferExercisesModel->getFightOfferExercises();
        return $this->render('window-fightOffers', compact('offers', 'exercises'));
    }

    public function actionShowOwnFightOffers()
    {
        $this->layout = false;
        $user = new User();
        $fightOfferExercisesModel = new FightOfferExercise();

        $ownOffers = $user->getFightOffersByFirstUserId(Yii::$app->user->identity['id']);
        $exercises = $fightOfferExercisesModel->getFightOfferExercises();
        return $this->render('window-ownFightOffers', compact('ownOffers', 'exercises'));
    }

    public function actionDeleteOwnFightOffer($id)
    {
        $this->layout = false;
        $user = new User();
        $user->deleteFightOfferById($id);
        $ownOffers = $user->getFightOffersByFirstUserId(Yii::$app->user->identity['id']);
        return $this->render('window-ownFightOffers', compact('ownOffers'));
    }

    public function actionVerify($token)
    {
        $user = User::findOne(['token' => $token]);
        if (!empty($user)) {
            if ($user->token == $token)
                $user->verified = '1';
            $user->save();
            return $this->render('verification');
        } else {
            return $this->goHome();
        }
    }

    public function actionChangePassword($token)
    {
        $user = User::findOne(['token' => $token]);
        $changingPasswordForm = new ChangingPasswordForm();

        if (isset($_POST['ChangingPasswordForm'])) {
            $changingPasswordForm->attributes = Yii::$app->request->post('ChangingPasswordForm');
            if ($changingPasswordForm->validate() && $changingPasswordForm->changePassword($user)) {
                return $this->goHome();
            }
        }

        if (!empty($user)) {
            return $this->render('changing-password', compact('changingPasswordForm'));
        } else {
            return $this->goHome();
        }
    }

    public function actionSendMailChangePassword()
    {
        $changingPasswordForm = new ChangingPasswordForm();
        $statusMail = $changingPasswordForm->sendMail();
        return $this->render('mail-changing-password', compact('statusMail'));
    }


    public function actionRole()
    {
//        $admin = Yii::$app->authManager->createRole('admin');
//        $admin->description = 'Администратор';
//        Yii::$app->authManager->add($admin);
//
//        $author = Yii::$app->authManager->createRole('author');
//        $author->description = 'Автор';
//        Yii::$app->authManager->add($author);
//
//        $competition_organizer = Yii::$app->authManager->createRole('competition_organizer');
//        $competition_organizer->description = 'Организатор соревнований';
//        Yii::$app->authManager->add($competition_organizer);
//
//        $user = Yii::$app->authManager->createRole('user');
//        $user->description = 'Пользователь';
//        Yii::$app->authManager->add($user);
//
//        $blocked_user = Yii::$app->authManager->createRole('blocked_user');
//        $blocked_user->description = 'Заблокированный пользователь';
//        Yii::$app->authManager->add($blocked_user);
//
//        $moderator = Yii::$app->authManager->createRole('moderator');
//        $moderator->description = 'Модератор';
//        Yii::$app->authManager->add($moderator);

        /*!!!*/
//        $permit = Yii::$app->authManager->createPermission('createCompetition');
//        $permit->description = 'Право на создание соревнования';
//        Yii::$app->authManager->add($permit);
//
//        $role_a = Yii::$app->authManager->getRole('competition_organizer');
//        $role_b = Yii::$app->authManager->getRole('moderator');
//        $role_c = Yii::$app->authManager->getRole('admin');
//        $permit_a = Yii::$app->authManager->getPermission('createCompetition');
//        Yii::$app->authManager->addChild($role_a, $permit_a);
//        Yii::$app->authManager->addChild($role_b, $permit_a);

views/site/authorization.php
<?php
$this->title = 'Авторизация';

use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<div class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <h1 align="center">Авторизация</h1>

        <?php
        $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'authorization-form']);
        ?>
        <?= $form->field($authorizationForm, 'login'); ?>
        <?= $form->field($authorizationForm, 'password')->passwordInput(); ?>
        <div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
        <a id="sign_up_url" href="<?= Url::to(['/site/registration']) ?>"> Зарегистрироваться</a>
        <?php
        ActiveForm::end();
        ?>
    </div>
</div>

views/site/book-cart.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
?>

<table width="100%">
    <?php
    $count = 0;
    if(!empty($books))
        for($i=0; $i<count($books); $i++):
            $count++;
            ?>
            <?php if (($count%4==0) || ($i==0)):?>
                <tr>
            <?php endif; ?>
                    <td>
                        <div class="book-modal-block">
                            <a href="<?= Url::to(['/book/view', 'id' => $books[$i]['id']]) ?>">
                                        <span class="book-block">
                                            <?= Html::img("@web/images/books/{$books[$i]['image']}", ['alt' => $books[$i]['name'], 'height' => '90px', 'width' => '70px']); ?>
                                        </span>
                            </a>
                            <h4>
                                <a href="<?= Url::to(['/book/view', 'id' => $books[$i]['id']]) ?>"><?=$books[$i]['name']  ?></a>
                                <i data-id="<?= $books[$i]['id'] ?>" class="fa fa-times delete-book" aria-hidden="true"></i>
                            </h4>
                        </div>
                    </td>
                <?php
                    if (($count%6==0) || ($i==2)):
                ?>
                </tr>
            <?php endif; ?>
    <?php endfor; ?>
</table>

views/site/changing-password.php
<?php
$this->title = 'Смена пароля';

use yii\widgets\ActiveForm;
?>
<div class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <h1 align="center">Смена пароля</h1>

        <?php
        $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'authorization-form']);
        ?>
        <?= $form->field($changingPasswordForm, 'login'); ?>
        <?= $form->field($changingPasswordForm, 'password')->passwordInput(); ?>
        <?= $form->field($changingPasswordForm, 'newPassword')->passwordInput(); ?>
        <?= $form->field($changingPasswordForm, 'newRepeatPassword')->passwordInput(); ?>
        <div>
            <button type="submit" class="btn btn-primary">Сменить пароль</button>
        </div>
        <?php
        ActiveForm::end();
        ?>
    </div>
</div>

views/site/edit-profile.php
<?php
$this->title = 'Редактирование профиля';

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
?>
<div class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <h1 align="center">Редактирование профиля</h1>

        <?php
        $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration-form']);
        ?>
        <?= $form->field($editProfileForm, 'last_name'); ?>
        <?= $form->field($editProfileForm, 'name'); ?>
        <?= $form->field($editProfileForm, 'patronymic'); ?>
        <?= $form->field($editProfileForm, 'image_avatar')->fileInput(); ?>
        <?= $form->field($editProfileForm, 'date_birth')->widget(DatePicker::className(), [
            'type' => DatePicker::TYPE_INPUT,
            'pluginOptions' => [
                'autoclose'=>true,
                'format' => 'yyyy-mm-dd'
            ]
        ]); ?>
        <?= $form->field($editProfileForm, 'experience')
            ->textInput(['placeholder' => 'Введите количество полных лет (одно число), например 4']); ?>
        <?= $form->field($editProfileForm, 'growth')
            ->textInput(['placeholder' => 'Введите одно число, например 172']); ?>
        <?= $form->field($editProfileForm, 'weight')
            ->textInput(['placeholder' => 'Введите одно число, например 67']); ?>
        <?= $form->field($editProfileForm, 'max_pulling_up')
            ->textInput(['placeholder' => 'Введите одно число, например 15']); ?>
        <?= $form->field($editProfileForm, 'max_push_up_bars')
            ->textInput(['placeholder' => 'Введите одно число, например 30']); ?>
        <?= $form->field($editProfileForm, 'max_push_up')
            ->textInput(['placeholder' => 'Введите одно число, например 55']); ?>
        <?= $form->field($editProfileForm, 'max_bench_press')
            ->textInput(['placeholder' => 'Введите одно число, например 100']); ?>
        <?= $form->field($editProfileForm, 'reference_youtube')
            ->textInput(['placeholder' => 'Введите ссылку на Ваш аккаунт в Youtube']); ?>
        <?= $form->field($editProfileForm, 'reference_vk')
            ->textInput(['placeholder' => 'Введите ссылку на Ваш аккаунт в VKontakte']); ?>
        <div>
            <button type="submit" class="btn btn-primary">Редактировать профиль</button>
            <a class="btn btn-success" href="<?= Url::to(['/site/send-mail-change-password']) ?>">Сменить пароль</a>
        </div>
        <?php
        ActiveForm::end();
        ?>
    </div>
</div>

views/site/index.php
<?php

$this->title = 'Главная';

use yii\helpers\Html;
use yii\helpers\Url;
?>

<!-- Slider -->
<section id="slider">
    <div id="slider_container" class="owl-carousel owl-theme">
        <?= Html::img('@web/images/1-slider.jpg', ['alt' => 'slide1', 'height' => '580px']); ?>
        <?= Html::img('@web/images/2-slider.jpg', ['alt' => 'slide2', 'height' => '580px']); ?>
        <?= Html::img('@web/images/3-slider.jpg', ['alt' => 'slide3', 'height' => '580px']); ?>
    </div>
</section>
<!-- End of slider -->

<!-- Latest news -->
<section class="latest-news">
    <h2>Что такое Street Workout?</h2>
    <div class="container-fluid">
        <div class="col-sm-4">
				<span class="news-block">
                    <?= Html::img('@web/images/1-latest_news.jpg', ['alt' => 'latest_news1', 'height' => '180px', 'width' => '280px']); ?>
					<p>
						Зародился Street Workout в Америке в 90-х годах, когда темнокожие подростки активно
                        работали над построением своего тела. В России Workout получил широкое распространение
                        в 2009 году.
					</p>
				</span>
        </div>
        <div class="col-sm-4">
				<span class="news-block">
					 <?= Html::img('@web/images/2-latest_news.jpg', ['alt' => 'latest_news2', 'height' => '180px', 'width' => '280px']); ?>
                    <p>
						Street Workout - это любительское спортивное направление. Включает в себя выполнение
                        различных упражнений на уличных спортплощадках.
					</p>
				</span>
        </div>
        <div class="col-sm-4">
				<span class="news-block">
					 <?= Html::img('@web/images/3-latest_news.jpg', ['alt' => 'latest_news3', 'height' => '180px', 'width' => '280px']); ?>
						<p>
                        Спортсмены могут выполнять различные элементы на турниках, брусьях, шведских стенках,
                        рукоходах и прочих конструкциях или вообще без их использования (на земле).
					</p>
				</span>
        </div>
    </div>
</section>
<!-- End of latest news -->

<!-- Popular tutorials -->
<section class="popular_tutorials">
    <h2>Популярные обучалки</h2>
    <div class="container-fluid">
        <?php foreach ($articles as $article): ?>
            <div class="col-md-6">
                <h3><?= $article['name']; ?></h3>
                <div class="video_tutorial">
                    <iframe width="560" height="315"
                            src="https://www.youtube.com/embed/<?= $article['video_link']; ?>" frameborder="0"
                            allow="autoplay; encrypted-media" allowfullscreen>
                    </iframe>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>
<!-- End of popular tutorials -->

views/site/mail-changing-password.php
<?php
$this->title = 'Смена пароля';

?>
<div class="container-fluid">
    <?php if($statusMail):?>
        <h3 align="center">Для смены пароля прочтите инструкцию, высланную Вам на почту.</h3>
    <?php endif;?>
    <?php if(!$statusMail):?>
        <h3 align="center">
            Для того, чтобы сменить пароль, необходимо сначала подтвердить почту.<br/>
            После регистрации Вам должно было прийти письмо подтвеждения почты.
        </h3>
    <?php endif;?>
</div>

views/site/profile.php
<?php
    $this->title = 'Личный кабинет';

    use yii\bootstrap\Modal;
    use yii\helpers\Html;
    use yii\helpers\Url;
?>

<div class="container-fluid">
    <div class="profile_block">
        <?= Html::img("@web/images/uploads/profile/{$imageName}",
            ['alt' => Yii::$app->user->identity['login'],
            'height' => '90px', 'width' => '100px', 'id' => 'avatar_img']); ?>
        <h2 align="center"><?=Yii::$app->user->identity['login']; ?></h2>
        ФИО:
        <?= Yii::$app->user->identity['last_name']; ?>
        <?= Yii::$app->user->identity['name']; ?>
        <?= Yii::$app->user->identity['patronymic']; ?><br/>
        Дата рождения:  <?= Yii::$app->user->identity['date_birth']; ?><br/>
        Стаж: <?= Yii::$app->user->identity['experience']; ?> года<br/>
        Рост: <?= Yii::$app->user->identity['growth']; ?><br/>
        Вес: <?= Yii::$app->user->identity['weight']; ?><br/>
        Максимальное количество подтягиваний: <?= Yii::$app->user->identity['max_pulling_up']; ?><br/>
        Максимальное количество отжиманий на брусьях: <?= Yii::$app->user->identity['max_push_up_bars']; ?><br/>
        Максимальное количество отжиманий от пола: <?= Yii::$app->user->identity['max_push_up']; ?><br/>
        Максимальный веса штанги при жиме лежа: <?= Yii::$app->user->identity['max_bench_press']; ?><br/>
        Прочитанные книги: <a href="#" onclick="return getBooks();">открыть список</a><br/>
        Изученные элементы: <a href="#" onclick="return getElements();">открыть список</a><br/>
        Предложения о зарубах: <a href="#" onclick="return getFightOffers();">открыть список</a><br/>
        Мои предложения о зарубах: <a href="#" onclick="return getOwnFightOffers();">открыть список</a><br/>
        <div class="profile_icon">
            <a href="<?= Yii::$app->user->identity['reference_vk']; ?>">
                <i class="fa fa-vk fa-5x profile_icon_vk" aria-hidden="true"></i>
            </a>
            <a href="<?= Yii::$app->user->identity['reference_youtube'];?>">
                <i class="fa fa-youtube fa-5x profile_icon_youtube" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</div>
<?php
    Modal::begin([
        'header' => '<h2>Прочитанные книги</h2>',
        'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
        'id' => 'modal-books',
    ]);
    Modal::end();

    Modal::begin([
        'header' => '<h2>Изученные элементы</h2>',
        'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
        'id' => 'modal-elements',
    ]);
    Modal::end();

    Modal::begin([
        'header' => '<h2>Предложения о зарубах</h2>',
        'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
        'size' => Modal::SIZE_LARGE,
        'id' => 'modal-fightOffers',
    ]);
    Modal::end();

    Modal::begin([
        'header' => '<h2>Мои предложения о зарубах</h2>',
        'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
        'size' => Modal::SIZE_LARGE,
        'id' => 'modal-fightOwnOffers',
    ]);
    Modal::end();
?>

views/site/registration.php
<?php
    $this->title = 'Регистрация';

    use yii\widgets\ActiveForm;
    use yii\helpers\Url;
?>
<div class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <h1 align="center">Регистрация</h1>

        <?php
            $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration-form']);
        ?>
        <?= $form->field($registrationForm, 'login'); ?>
        <?= $form->field($registrationForm, 'email'); ?>
        <?= $form->field($registrationForm, 'password')->passwordInput(); ?>
        <?= $form->field($registrationForm, 'repeatPassword')->passwordInput(); ?>
        <a href="<?= Url::to(['/rules']) ?>">Правила сообщества</a>
        <?= $form->field($registrationForm, 'acceptingRules')->checkbox()?>
        После регистрации подтвердите почту!
        <div>
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </div>
        <?php
            ActiveForm::end();
        ?>
    </div>
</div>

views/site/rules.php
Правила

views/site/verification.php
<?php

$this->title = 'Подтверждение почты';
?>

<div class="container-fluid">
    <h3 align="center">Почта успешно потверждена. Желаем Вам хорошего времяпрепровождения на нашем сайте.</h3>
</div>

views/site/view-user.php
<?php
$this->title = $user['login'];

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="container-fluid">
    <div class="profile_block">
        <?= Html::img("@web/images/uploads/profile/{$user['image_avatar']}",
            ['alt' => Yii::$app->user->identity['login'],
                'height' => '90px', 'width' => '100px', 'id' => 'avatar_img']); ?>
        <h2 align="center"><?=$user['login'];?></h2>
        ФИО:
        <?=$user['last_name'];?>
        <?=$user['name'];?>
        <?=$user['patronymic'];?> <br/>
        Дата рождения:  <?=$user['date_birth'];?><br/>
        Стаж: <?=$user['experience'];?> года<br/>
        Рост: <?=$user['growth'];?><br/>
        Вес: <?=$user['weight'];?><br/>
        Максимальное количество подтягиваний: <?=$user['max_pulling_up'];?><br/>
        Максимальное количество отжиманий на брусьях: <?= $user['max_push_up_bars']; ?><br/>
        Максимальное количество отжиманий от пола: <?=$user['max_push_up']; ?><br/>
        Максимальный веса штанги при жиме лежа: <?=$user['max_bench_press']; ?><br/>
        <div class="profile_icon">
            <a href="<?= $user['reference_vk']; ?>">
                <i class="fa fa-vk fa-5x profile_icon_vk" aria-hidden="true"></i>
            </a>
            <a href="<?= $user['reference_youtube']; ?>">
                <i class="fa fa-youtube fa-5x profile_icon_youtube" aria-hidden="true"></i>
            </a>
        </div>
        <?php if(!Yii::$app->user->isGuest): ?>
            <a id="offer_fight_btn" href="#" class="btn btn-success" onclick="return offerFight(<?=$user['id'];?>);">
                Вызвать на зарубу
            </a><br/>
        <?php endif; ?>
    </div>
</div>

<?php
Modal::begin([
    'header' => '<h2>Вызвать на зарубу</h2>',
    'footer' => '<button type="button" data-dismiss="modal" class="btn btn-success"> Закрыть </button>',
    'id' => 'modal-fight',
]);
Modal::end();

views/site/window-elements.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>

<table width="100%">
    <?php
    $count = 0;
    if(!empty($elements))
        for($i=0; $i<count($elements); $i++):
            $count++;
            ?>
            <?php if (($count%4==0) || ($i==0)):?>
            <tr>
        <?php endif; ?>
            <td>
                <div class="element-modal-block">
                    <span class="element-window">
                        <?= Html::img("@web/images/elements/{$elements[$i]['level']}lvl/{$elements[$i]['image']}",
                            ['alt' => $elements[$i]['name'], 'height' => '70px', 'width' => '70px']); ?>
                    </span>
                    <h4>
                        <?=$elements[$i]['name']  ?>
                        <i data-id="<?= $elements[$i]['id'] ?>" class="fa fa-times delete-element" aria-hidden="true"></i>
                    </h4>
                </div>
            </td>
            <?php
            if (($count%6==0) || ($i==2)):
                ?>
                </tr>
            <?php endif; ?>
        <?php endfor; ?>
</table>

views/site/window-fightOffers.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="fightOffers">
    <table width="100%" border="1">
        <th>Логин пользователя</th>
        <th>Город</th>
        <th>Адрес площадки</th>
        <th>Дата зарубы</th>
        <th>Упражнения</th>
        <th></th>
        <th></th>
        <?php if(!empty($offers))
                foreach ($offers as $offer):
        ?>
        <tr>
            <td><?= $offer['login']?></td>
            <td><?= $offer['city']?></td>
            <td><?= $offer['playground_address']?></td>
            <td><?= $offer['date_fight']?></td>
            <td>
                <?php
                foreach ($exercises as $exercise)
                    if($offer['id_offer'] == $exercise['id_fight_offer'])
                        echo $exercise['name_exercise']."<br/>";
                ?>
            </td>
            <td>
                <i data-id="<?= $offer['id_offer'] ?>" class="fa fa-plus accept-fight" aria-hidden="true"></i>
            </td>
            <td>
                <i data-id="<?= $offer['id_offer'] ?>" class="fa fa-times delete-fightOffer" aria-hidden="true"></i>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

views/site/window-ownFightOffers.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="fightOffers">
    <table width="100%" border="1">
        <th>Логин пользователя</th>
        <th>Город</th>
        <th>Адрес площадки</th>
        <th>Дата зарубы</th>
        <th>Упражнения</th>
        <th></th>
        <?php if(!empty($ownOffers))
            foreach ($ownOffers as $ownOffer):
                ?>
                <tr>
                    <td><?= $ownOffer['login']?></td>
                    <td><?= $ownOffer['city']?></td>
                    <td><?= $ownOffer['playground_address']?></td>
                    <td><?= $ownOffer['date_fight']?></td>
                    <td>
                        <?php
                        foreach ($exercises as $exercise)
                            if($ownOffer['id_offer'] == $exercise['id_fight_offer'])
                                echo $exercise['name_exercise']."<br/>";
                        ?>
                    </td>
                    <td><i data-id="<?= $ownOffer['id_offer'] ?>" class="fa fa-times delete-ownFightOffer" aria-hidden="true"></i></td>
                </tr>
            <?php endforeach; ?>
    </table>
</div>