controllers/MapController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SportsFacility;
use app\models\SportsFacilityCreatingForm;
use app\models\ImageUploading;
use app\models\SportsFacilityMark;
use app\models\CommentForm;
use yii\web\Controller;
use yii\web\UploadedFile;

class MapController extends Controller
{
    public function actionIndex()
    {
        $sportsFacilityModel = new SportsFacility();
        $sportsObjects = $sportsFacilityModel->getSportsObjects();

        return $this->render('index', compact('sportsObjects'));
    }

    public function actionView($id)
    {
        $sportsFacilityModel = new SportsFacility();
        $sportsObject = $sportsFacilityModel->getSportsObjectById($id);

        $averageMarkFacility = SportsFacilityMark::find()->where(['id_facility' => $id])->average('value');
        $averageMarkFacility = round($averageMarkFacility, 1);

        $commentForm = new CommentForm();
        if (isset($_POST['CommentForm'])) {
            $commentForm->attributes = Yii::$app->request->post('CommentForm');
            if ($commentForm->validate()) {
                $commentForm->writeFacilityComment($id);
            }
        }
        $commentFacility = $sportsFacilityModel->getFacilityComment($id);
        return $this->render('view', compact('sportsObject',
            'commentForm', 'commentFacility', 'averageMarkFacility'));
    }

    public function actionCreating()
    {
        $creatingForm = new SportsFacilityCreatingForm();
        $imageUploadingModel = new ImageUploading();

        if (isset($_POST['SportsFacilityCreatingForm'])) {
            $creatingForm->attributes = Yii::$app->request->post('SportsFacilityCreatingForm');

            $typeImage = 'sportsFacility';
            $file = UploadedFile::getInstance($creatingForm, 'main_image');
            $nameImage = $imageUploadingModel->uploadImage($file, $typeImage);
            $creatingForm->main_image = $nameImage;

            if ($creatingForm->validate() && $creatingForm->createFacility()) {
                return $this->redirect('/map/index');
            }
        }
        return $this->render('creating', compact('creatingForm'));
    }

    public function actionRateFacility($id, $mark)
    {
        $markFacility = SportsFacilityMark::findOne([
            'id_user' => Yii::$app->user->identity['id'],
            'id_facility' => $id
        ]);

        if (!isset($markFacility)) {
            $facilityMarkModel = new SportsFacilityMark();
            $facilityMarkModel->id_facility = $id;
            $facilityMarkModel->id_user = Yii::$app->user->identity['id'];
            $facilityMarkModel->value = $mark;
            $facilityMarkModel->save();
        } else {
            $markFacility->value = $mark;
            $markFacility->save();
        }

        return true;
    }
}

views/map/creating.php
<?php
$this->title = 'Создание спортивного объекта';

use yii\widgets\ActiveForm;
?>
<div class="container-fluid">
    <h3 align="center">Создание спортивного объекта на карте</h3>
    <div class="col-md-5 col-md-offset-4 form-creating">
        <?php
        $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'registration-form']);
        ?>
        <?= $form->field($creatingForm, 'name_facility')
            ->textInput(['placeholder' => 'Введите название объекта, например "Современная Workout-площадка"']); ?>
        <?= $form->field($creatingForm, 'address')
            ->textInput(['placeholder' => 'Введите адрес объекта, например парк Пушкина или ул.Ленина 34']); ?>
        <?= $form->field($creatingForm, 'main_image')->fileInput(); ?>
        <?= $form->field($creatingForm, 'latitude')->textInput(['value' => $_COOKIE['lat'],
            'placeholder' =>'Введите широту расположения объекта, например 55.161017']); ?>
        <?= $form->field($creatingForm, 'longitude')->textInput(['value' => $_COOKIE['lng'],
            'placeholder' => 'Введите долготу расположения объекта, например 61.327743']); ?>
        <?= $form->field($creatingForm, 'description')->textarea(['placeholder' => 'Необязательное поле']); ?>
        <div>
            <button type="submit" class="btn btn-primary">Создать объект</button>
        </div>
        <?php
        ActiveForm::end();
        ?>
    </div>
</div>

views/map/index.php
<?php

$this->title = 'Карта площадок';

use yii\helpers\Url;
use yii\helpers\Html;
?>

<?php if (isset($_COOKIE['lat']) && isset($_COOKIE['lng'])) {
    $lat = $_COOKIE["lat"];
    $lng = $_COOKIE["lng"];
}?>
<h3 align="center">Карта площадок и тренажерных залов</h3>
<h4><a class="btn btn-success" target="_blank" href="<?= Url::to(['/map/creating']) ?>">Создать объект на карте</a></h4>
Координаты для создания объекта на карте:
<span id="clicked_element">отсутствуют (нажмите на необходимую точку на карте)</span>

<script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>

<div id="map" style="width:100%; height:500px"></div>

<script type="text/javascript">
    var map,
        clickedElement = document.getElementById('clicked_element');

    DG.then(function () {
        map = DG.map('map', {
            center: [55.15402, 61.42915],
            zoom: 11
        });

        map.locate({setView: true, watch: true})
            .on('locationfound', function(e) {
                DG.marker([e.latitude, e.longitude]).addTo(map);
            })
            .on('locationerror', function(e) {
                DG.popup()
                    .setLatLng(map.getCenter())
                    .setContent('Доступ к определению местоположения отключён')
                    .openOn(map);
            });

        map.on('click', function(e) {
            clickedElement.innerHTML = e.latlng.lat + ', ' + e.latlng.lng;
            document.cookie = "lat=" + e.latlng.lat
                + "; path=/map/creating";
            document.cookie = "lng=" + e.latlng.lng
                + "; path=/map/creating";
        });
        <?php
            foreach ($sportsObjects as $sportsObject):
        ?>
            DG.marker([<?= $sportsObject['latitude'];?>,
                <?= $sportsObject['longitude'];?>]).addTo(map)
                .bindPopup('<?= Html::img("@web/images/uploads/sports_objects/{$sportsObject['main_image']}",
                    ['alt' => $sportsObject['name_facility'], 'height' => '90px', 'width' => '120px', 'class' => 'map_img']);?>'+
                    '<p class="map_description" align="center"><?= $sportsObject['name_facility'];?>'+
                    '<br/>Создатель метки: '+
                    '<a href="<?=Url::to(['/site/view-user', 'id' => $sportsObject['id_author']]);?>">'+
                    '<?= $sportsObject['login']; ?></a>'+
                    '<br/>Адрес: <?= $sportsObject['address'];?>'+
                    '<br/><a href="<?= Url::to(['/map/view', 'id' => $sportsObject['id_facility']])?>">Подробнее</a></p>')
                .bindLabel('<?= $sportsObject['name_facility'];?> <br/><?= $sportsObject['address'];?>');
                <?php endforeach;?>
        DG.control.location().addTo(map);
    });
</script>

views/map/view.php
<?php

$this->title = $sportsObject[0]['name_facility'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $sportsObject[0]['name_facility']]);

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>

<section class="sports_facility">
    <div class="container-fluid">
        <div class="row">
            <?php if(!empty($sportsObject)): ?>
            <div class="col-md-3 col-md-offset-2">
                <?= Html::img("@web/images/uploads/sports_objects/{$sportsObject[0]['main_image']}",
                    ['alt' => $sportsObject[0]['name_facility'], 'height' => '240px', 'width' => '240px', 'id' => 'img-book']); ?>
            </div>
            <div class="col-md-4">
                <span class="facility-block">
                    <span class="headers_3"><?=$sportsObject[0]['name_facility']  ?></span> <br/>
                        <span class="headers_4">Автор:</span>
                    <a href="<?= Url::to(['/site/view-user', 'id' => $sportsObject[0]['id_author']]) ?>">
                        <?= $sportsObject[0]['login']; ?></a><br/>
                        <span class="headers_4">Описание:</span><br/>
                    <?= $sportsObject[0]['description']; ?><br/>
                    <?php if(!Yii::$app->user->isGuest): ?>
                        <span class="headers_4">Средняя оценка:</span>
                        <?= $averageMarkFacility; ?><br/>
                        <span class="headers_4">Оценить:</span>
                        <a class="rate_facility" data-id="<?=$sportsObject[0]['id_facility']?>" data-mark="1" href="<?= Url::to(['map/rate-facility',
                            'id' => $sportsObject[0]['id_facility'], 'mark' => 1]) ?>">☆</a>
                        <a class="rate_facility" data-id="<?=$sportsObject[0]['id_facility']?>" data-mark="2" href="<?= Url::to(['map/rate-facility',
                            'id' => $sportsObject[0]['id_facility'], 'mark' => 2]) ?>">☆</a>
                        <a class="rate_facility" data-id="<?=$sportsObject[0]['id_facility']?>" data-mark="3" href="<?= Url::to(['map/rate-facility',
                            'id' => $sportsObject[0]['id_facility'], 'mark' => 3]) ?>">☆</a>
                        <a class="rate_facility" data-id="<?=$sportsObject[0]['id_facility']?>" data-mark="4" href="<?= Url::to(['map/rate-facility',
                            'id' => $sportsObject[0]['id_facility'], 'mark' => 4]) ?>">☆</a>
                        <a class="rate_facility" data-id="<?=$sportsObject[0]['id_facility']?>" data-mark="5" href="<?= Url::to(['map/rate-facility',
                            'id' => $sportsObject[0]['id_facility'], 'mark' => 5]) ?>">☆</a><br/>
                    <?php endif; ?>
                </span>
            </div>
        </div>

            <div class="row">
                <div class="col-md-3 col-md-offset-2">
                    <?php if(!Yii::$app->user->isGuest): ?>
                        <div>
                            <span class="headers_3">Написать отзыв:</span>
                            <?php
                            $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'comment-form']);
                            ?>
                            <?= $form->field($commentForm, 'text')->textarea(); ?>
                            <div>
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                            <?php
                            ActiveForm::end();
                            ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">
                <div class="reviews">
                    <div class="col-md-4 col-md-offset-2">
                        <span class="headers_3">Отзывы:</span> <br/>
                        <?php
                        if(!empty($commentFacility))
                            foreach ($commentFacility as $commentFacility){
                                echo '<span class="headers">'.$commentFacility['login'].'</span>'.' : ';
                                echo $commentFacility['content'].'<br/>';
                            }
                        ?>
                    </div>
                </div>
            </div>

    </div>
        <?php endif; ?>
</section>